name: GitHub Data Pipeline

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

env:
  GITHUB_REPO_DATABASE: test
  GITHUB_PERSONAL_DATABASE: github_personal
  USER_LOGIN: cmuc24
  REPO_FULL_NAME: runtipi/runtipi

jobs:
  github_repos_pipeline:
    name: GitHub Repos Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: hooopo/repo-track-pipeline@main
        with:
          access-token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          database-url: ${{ secrets.DATABASE_URL }}/${{ env.GITHUB_REPO_DATABASE || 'github_repos' }}
          repo-full-name: ${{ env.REPO_FULL_NAME }}

  github_personal_pipeline:
    name: GitHub Personal Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: hooopo/oh-my-github-pipeline@main
        with:
          access-token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          database-url: ${{ secrets.DATABASE_URL }}/${{ env.GITHUB_PERSONAL_DATABASE || 'github_personal' }}
          user-login: ${{ env.USER_LOGIN || github.repository_owner }}
